openedx/frontend-template-application

config/webpack.common.config.js
config/webpack.dev.config.js
config/webpack.prod.config.js

Adds comments to the Webpack configs.
I also made a couple non-documentation changes:
1. Renamed the "assets" entry to "app". I think that was a copy-and-paste from studio-frontend.
2. Remove CSS modules config from the css-loader options.
`modules: true` paired with `localIdentName: [local]` doesn't change any class names. Also, I didn't see anything in this project that was importing CSS/Sass, so I don't think it is needed. I wouldn't want people copying it into their new projects unless they understood what it did and needed it. If this cookie cutter ever ends up using CSS modules, then we can add it back.

fix(webpack): remove css modules and add comments

---

Makefile
config/webpack.prod.config.js
package.json

Webpack generates several JS files during our production build. This PR address issue #24 of getting our production build to properly inject the multiple files into `index.html` such that when the files are deployed to gh-pages, it will work as expected.
Running this locally, we can see from the screenshots that files with chunkhashes are being included in index.html and the 🍪 ✂️ app runs properly in the browser:

build(gh-pages): deploy production build to gh-pages

---

config/webpack.prod.config.js

The usage of `html-webpack-plugin` was missing from our `config/webpack.prod.config.js` file, which prevented the CSS/JS from being injected into `index.html` on production builds. This is in the main `front-end-cookie-cutter` app so I'm not sure how it got removed in our branch. 🤷‍♂️
Related: The "flash of unstyled content" (FOUC) is only an issue when running the app locally with `webpack-dev-server` as it's loading all CSS within the Javascript which takes time to load into the DOM on initial page load. The production build extracts the CSS into their own files and injects them into `index.html`, so FOUC isn't an issue for production builds.

fix(prod-build): adds missing html-webpack-plugin for production builds

---

config/webpack.common.config.js

Without this, webpack will write relative urls for assets like CSS font url() methods.
And since CSS urls don't follow the `<base href="/">` specified in `<head>`, if your current URL is deeper than the toplevel, any local web font references or other url() method calls will not find their target. 
(It came up in publisher-frontend when trying to use FontAwesome webfonts.)

Add publicPath webpack setting so nested URLs can find assets

---

.travis.yml
README.md
documentation/.travis.yml.md

Since late 2018, greenkeeper handles lockfiles for public packages itself.
https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0
Repos with private packages might still want greenkeeper-lockfile, but that can be a custom thing, rather than the default cookiecutter.

Drop use of greenkeeper-lockfile

---

__mocks__/fileMock.js

Resolves issue #76 by adding `__mocks__/fileMock.js`.

Adding fileMock.js for mocking static assets in Jest tests

---

config/webpack.dev.config.js
config/webpack.prod.config.js
package-lock.json
package.json

Adds `image-webpack-loader` to webpack.dev.config and webpack.prod.config to properly handle images.

Add image-webpack-loader to webpack dev and prod configs

---

src/App.scss

When using Paragon components that use font-awesome icons (e.g., `<Icon />`) or just any font-awesome classes, they currently do not load until we include these 2 lines.

Import font-awesome in App.scss

---

docs/how_tos/i18n.rst

i18n now looks for a user preference in a cookie before looking at the browser language.

docs: update i18n locale selection

---

.travis.yml

Travis builds will currently fail if `npm run lint` returns any errors.
This change will make them also fail if `npm run lint` returns any warnings.
This is based on my observation that messages that do not block merging will often go ignored, eventually leading to a situation where they are too noisy to be useful and too overwhelming to fix. For example, pylint warnings in edx-platform were ignored for a 2-ish year time period, during which the warning count grew to ~2,500.

Disallow eslint warnings for Travis build

---

jest.config.js

This was a change I've had to make in multiple MFEs to be able to use @testing-library/jest-dom and its extend-expect functionality, which adds a bunch of new DOM assertions to expectations.  Very useful.  From reading around a bit, it seems like setupFilesAfterEnv is more generally what we'd want to use, so I'm hoping this will save someone else the Google search I've now done multiple times.

Update jest.config.js to use setupFilesAfterEnv

---

package.json

If you too forget what language you're working in and thus miss adding 800 semi-colons, this new command is for you!
While I've never had issues with the fix flag, I imagine there could be cases where we don't agree with its changes and thus may want the option to run without it, which is why I leave the original lint wherever I go (also because that command isn't going to work on CI)

chore: add fix flag for linter

---

README-template-frontend-app.rst
README.rst

Add a template README for new MFEs to use.
Purpose: Help internal & external devs self serve by understanding the whats and whys of your MFE
https://openedx.atlassian.net/browse/TNL-8081

docs: Add template README for MFEs

---

Makefile

Docs: https://developers.transifex.com/docs/using-the-client
Apparently this CLI option changed from singular to plural at some point.

fix: Fix pull_translations by using correct CLI flag for language filter

---

.github/workflows/ci.yml
package-lock.json
package.json

* Removes custom `browserslist` configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
* Removes `is-es5` check in CI since ES5 was only needed for IE 11 support which is dropped. The supported browsers defined by the shared configuration all [natively support ES6](https://caniuse.com/?search=es6).
This change reduces the resultant asset bundle size.
* Update `edx/paragon` version

build: use shared browserslist configuration and upgrade paragon version

---

.github/workflows/ci.yml
Makefile

`npm ci` never produces lockfile changes so it makes no sense to check for such changes here. Including this serves only to confuse people about how node dependency management works.

build: remove superfluous check for lockfile changes

---

src/example/ExamplePage.jsx

Running the example app immediately throws a JS error due to nothing being returned by the `ExamplePage` component:
This PR fixes it:

fix: ensure ExamplePage renders without JS error

---

.tx/config
Makefile
package-lock.json
package.json

**Ticket**
[Updating /api/v2 transifex endpoints](https://github.com/edx/edx-arch-experiments/issues/202)
**What has changed?**
- Update Makefile commands for new v3 transifex API
- Add edx/reactifex as a dependency
- Add Transifex config file
**Reference PR**
https://github.com/openedx/frontend-app-learning/pull/837

Update transifex api from v2 to v3

---

Makefile
package-lock.json
package.json
src/i18n/index.js
src/index.jsx

- Bump frontend-platform to bring intl-imports.js script
- Move all i18n imports into `src/i18n/index.js` so intl-imports.js can override it with latest translations
- Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.
- This pull request creates conflicts with https://github.com/openedx/frontend-template-application/pull/556, but it's rather easy conflicts to resolve in `package.json`
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Join the conversation on [Open edX Slack …

feat: use `atlas` in `make pull_translations`

---

README-template-frontend-app.rst
README.rst

My understanding is that security reports should go to security@openedx.org: Project-related communications should use the project email domain, not the organization domain.
@feanil True?

docs: security reports should go to security@openedx.org

---

Makefile

This is a follow up to https://github.com/openedx/frontend-template-application/pull/612 . #612 should have included the changes but apparently OEP-58 needs more publicity.
Testing
--------
I've ran the following:
```
$ OPENEDX_ATLAS_PULL=yes make pull_translations
$ cat src/i18n/index.js
```
Generates the following code, which seems to be good:
```js
// This file is generated by the openedx/frontend-platform's "intl-import.js" script.
//
// Refer to the i18n documents in https://docs.openedx.org/en/latest/developers/references/i18n.html to update
// the file and use the Micro-frontend i18n pattern in new repositories.
//
import messagesFromParagon from './messages/paragon';
import messagesFromFrontendComponentHeader from './messages/frontend-component-header';
import …
```

feat: include paragon in atlas pull as well

---

.github/workflows/ci.yml

As a first step in the upgrade to Node 20, add it to the CI matrix as a non-blocking test.
See [the tracking issue](https://github.com/openedx/frontend-template-application/issues/742) for further information.

ci: Add Node 20 to CI matrix

---

.github/workflows/lockfileversion-check.yml

This bug was introduced in the recent [Node 20 Upgrade PR](https://github.com/openedx/frontend-template-application/pull/744).  It should refer to this:
https://github.com/openedx/.github/blob/master/.github/workflows/lockfileversion-check-v3.yml

test: fix lockfile workflow filename

---

public/index.html

The purpose of this PR is that whenever a new frontend app is created from this template, it shouldn't show `App Template | null` in case `process.env.SITE_NAME` is null. This kind of issue arose in [`frontend-app-auth` ](https://github.com/openedx/frontend-app-authn/pull/1185)and resolved there resulting in similar change requirement in this repository.
For detailed context, see this [#1158](https://github.com/openedx/frontend-app-authn/issues/1158)

Browser header showing null

---

.github/workflows/ci.yml

And since codecov@v4 no longer supports tokenless uploading, use the global org token to do so.
(It seems that generating it has finally been rolled out to our org.)

test: Bump codecov to v4

---

docs/decisions/0002-feature-based-application-organization.rst

There is a typo in the architecture doc for the template application. While this doc is still in the "proposed" state, it has been around for about 5 years and has been copied over into most of our MFEs. Whether or not it is actually accepted is another topic for a large group of people, but I figure fixing typos can't hurt.

fix: docs typo

---

package-lock.json
package.json

When creating a new MFE with tutor and mounting it for development, the image build fails because atlas does not exist during the pull_translations step.
Atlas has been a necessary part of the image build process since #576 to pull translations and we now add it as a dependency from start so that the build step does not fail.

fix: add openedx-atlas as a dependency
